[[redirects]]
  from = "/calculator-api/*"
  to = "http://ec2-18-219-104-49.us-east-2.compute.amazonaws.com:8000/:splat"
  status = 200

[[redirects]]
  from = "/scraping-api/*"
  to = "http://ec2-18-216-33-231.us-east-2.compute.amazonaws.com:8000/:splat"
  status = 200
